name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
        with:
          node-version: 24
          cache-key-prefix: lint

      - name: Install dependencies
        run: yarn install

      - name: Format and Lint check
        run: yarn check-tsc && yarn lint && yarn build && yarn check-exports

  test:
    runs-on: ubuntu-latest
    needs: lint # Only run tests if linting passes

    strategy:
      matrix:
        node-version: [20, 22, 24]
        graphql-version: [15, 16, 17.0.0-alpha.9]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
        with:
          node-version: ${{ matrix.node-version }}
          cache-key-prefix: test

      - name: Use GraphQL v${{matrix.graphql-version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql-version}}

      - name: Install dependencies
        run: |
          yarn config set enableImmutableInstalls false
          yarn install

      - name: Tests and Coverage
        run: yarn test --coverage
